apiVersion: v1
kind: Service
metadata:
  name: my-app-service-prod
  namespace: prod
spec:
  selector:
    app: my-app
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80

